name: mongo-sharding-repl

services:
  # Config Servers Replica Set
  configSrv1:
    container_name: repl-configSrv1
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --configsvr --replSet configReplSet --port 27017 --dbpath /data/db
    volumes:
      - configSrv1_data:/data/db

  configSrv2:
    container_name: repl-configSrv2
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --configsvr --replSet configReplSet --port 27017 --dbpath /data/db
    volumes:
      - configSrv2_data:/data/db

  configSrv3:
    container_name: repl-configSrv3
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --configsvr --replSet configReplSet --port 27017 --dbpath /data/db
    volumes:
      - configSrv3_data:/data/db

  # Shard 1 Replica Set (3 replicas)
  shard1-1:
    container_name: repl-shard1-1
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --shardsvr --replSet shard1ReplSet --port 27017 --dbpath /data/db
    volumes:
      - shard1_1_data:/data/db

  shard1-2:
    container_name: repl-shard1-2
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --shardsvr --replSet shard1ReplSet --port 27017 --dbpath /data/db
    volumes:
      - shard1_2_data:/data/db

  shard1-3:
    container_name: repl-shard1-3
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --shardsvr --replSet shard1ReplSet --port 27017 --dbpath /data/db
    volumes:
      - shard1_3_data:/data/db

  # Shard 2 Replica Set (3 replicas)
  shard2-1:
    container_name: repl-shard2-1
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --shardsvr --replSet shard2ReplSet --port 27017 --dbpath /data/db
    volumes:
      - shard2_1_data:/data/db

  shard2-2:
    container_name: repl-shard2-2
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --shardsvr --replSet shard2ReplSet --port 27017 --dbpath /data/db
    volumes:
      - shard2_2_data:/data/db

  shard2-3:
    container_name: repl-shard2-3
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --shardsvr --replSet shard2ReplSet --port 27017 --dbpath /data/db
    volumes:
      - shard2_3_data:/data/db

  # Mongos Router
  mongos:
    container_name: repl-mongos
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongos --configdb configReplSet/configSrv1:27017,configSrv2:27017,configSrv3:27017 --bind_ip_all --port 27017
    depends_on:
      - configSrv1
      - configSrv2
      - configSrv3
      - shard1-1
      - shard1-2
      - shard1-3
      - shard2-1
      - shard2-2
      - shard2-3

  # Application
  pymongo_api:
    container_name: repl-pymongo_api
    build:
      context: api_app
      dockerfile: api_app/Dockerfile
    depends_on:
      - mongos
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://mongos:27017"
      MONGODB_DATABASE_NAME: "somedb"

volumes:
  configSrv1_data:
  configSrv2_data:
  configSrv3_data:
  shard1_1_data:
  shard1_2_data:
  shard1_3_data:
  shard2_1_data:
  shard2_2_data:
  shard2_3_data:
